apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: myapp-dev

bases:
  - ../../base

namePrefix: dev-

commonLabels:
  environment: dev

patches:
  - path: replica-count.yaml
  - path: resource-limits.yaml

configMapGenerator:
  - name: myapp-config
    behavior: merge
    literals:
      - environment=dev
      - log_level=debug
