apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: myapp-production

bases:
  - ../../base

namePrefix: prod-

commonLabels:
  environment: production

patches:
  - path: replica-count.yaml
  - path: resource-limits.yaml

resources:
  - hpa.yaml

configMapGenerator:
  - name: myapp-config
    behavior: merge
    literals:
      - environment=production
      - log_level=warn
